AWSTemplateFormatVersion: 2010-09-09
Description: >
  CloudFormation template for Stock Analysis Platform (Live)
  Architecture includes ALB, Auto Scaling Group, EC2, RDS, DynamoDB,
  Lambda (event-based), S3 Data Lake, AWS Glue, EMR, and Cognito.

Parameters:
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnet1CIDR:
    Type: String
    Default: 10.0.1.0/24
  PublicSubnet2CIDR:
    Type: String
    Default: 10.0.2.0/24
  PrivateSubnet1CIDR:
    Type: String
    Default: 10.0.3.0/24
  PrivateSubnet2CIDR:
    Type: String
    Default: 10.0.4.0/24
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
  DBUser:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true

Resources:
  ### --- Networking ---
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: StockAppVPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: PublicSubnet1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: PublicSubnet2

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: PrivateSubnet1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: PrivateSubnet2

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  ### --- Security Groups ---
  InstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP/HTTPS from internet
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  # NEW: Separate DB security group – only EC2 (InstanceSG) can access Postgres
  DBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Postgres from app instances only
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref InstanceSG
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  EMRSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EMR cluster
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          SourceSecurityGroupId: !Ref EMRSG
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  ### --- S3 Data Lake (matches two buckets in diagram) ---
  StockPricesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "stock-prices-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled

  NewsArticlesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "news-articles-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled

  ### --- EC2 Auto Scaling + Load Balancer ---
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: ami-0c55b159cbfafe1f0  # replace with latest in your region
        InstanceType: t3.micro
        KeyName: !Ref KeyPairName
        SecurityGroupIds:
          - !Ref InstanceSG
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y python3 git
            cd /home/ec2-user
            git clone https://github.com/cloudy0310/INF-2003-INF-2006-.git
            cd INF-2003-INF-2006-
            pip3 install -r requirements.txt
            # run Streamlit main app (adjust path if needed)
            nohup streamlit run app.py --server.port 80 --server.address 0.0.0.0 &

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: StockAppALB
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref InstanceSG

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPC
      TargetType: instance
      HealthCheckPath: /

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: 2
      MaxSize: 4
      DesiredCapacity: 2
      TargetGroupARNs:
        - !Ref TargetGroup

  ### --- RDS (PostgreSQL) ---
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: stockapp-db
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref DBSG
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false

  ### --- DynamoDB ---
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: StockNews
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: news_id
          AttributeType: S
      KeySchema:
        - AttributeName: news_id
          KeyType: HASH

  ### --- IAM Roles for Lambda / Glue / EMR ---
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Policies:
        - PolicyName: LambdaS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${StockPricesBucket.Arn}"
                  - !Sub "${StockPricesBucket.Arn}/*"
                  - !Sub "${NewsArticlesBucket.Arn}"
                  - !Sub "${NewsArticlesBucket.Arn}/*"

  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GlueDataLakeAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${StockPricesBucket.Arn}"
                  - !Sub "${StockPricesBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:BatchWriteItem
                Resource: !GetAtt DynamoDBTable.Arn

  EMRServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: elasticmapreduce.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole

  EMRJobFlowRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role
      Policies:
        - PolicyName: EMRS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${NewsArticlesBucket.Arn}"
                  - !Sub "${NewsArticlesBucket.Arn}/*"
                  - !Sub "${StockPricesBucket.Arn}"
                  - !Sub "${StockPricesBucket.Arn}/*"

  EMRInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EMRJobFlowRole

  ### --- Lambda Functions + EventBridge Rules ---
  LambdaStockEvent:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: FetchStockData
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def handler(event, context):
              print("Fetching stock data...")
      Runtime: python3.12
      Timeout: 60

  LambdaNewsEvent:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SummarizeNews
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def handler(event, context):
              print("Summarizing news articles...")
      Runtime: python3.12
      Timeout: 60

  StockEventRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 day)
      Targets:
        - Arn: !GetAtt LambdaStockEvent.Arn
          Id: StockTarget

  NewsEventRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(30 minutes)
      Targets:
        - Arn: !GetAtt LambdaNewsEvent.Arn
          Id: NewsTarget

  # NEW: Allow EventBridge to invoke Lambdas
  AllowEventsInvokeStockLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaStockEvent
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt StockEventRule.Arn

  AllowEventsInvokeNewsLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaNewsEvent
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt NewsEventRule.Arn

  ### --- (Optional) Glue Job + EMR Cluster skeletons ---
  GlueJobComputeIndicators:
    Type: AWS::Glue::Job
    Properties:
      Name: compute-indicators-job
      Role: !Ref GlueServiceRole
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${StockPricesBucket}/scripts/compute_indicators.py"
        PythonVersion: "3"
      GlueVersion: "4.0"
      MaxRetries: 0
      NumberOfWorkers: 2
      WorkerType: G.1X

  EMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: FinancialNewsNLPCluster
      ReleaseLabel: emr-6.13.0
      Applications:
        - Name: Spark
      ServiceRole: !Ref EMRServiceRole
      JobFlowRole: !Ref EMRInstanceProfile
      VisibleToAllUsers: true
      Instances:
        Ec2SubnetId: !Ref PrivateSubnet1
        Ec2SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: m5.xlarge
          Name: Master
        CoreInstanceGroup:
          InstanceCount: 2
          InstanceType: m5.large
          Name: Core
        TerminationProtected: false
        KeepJobFlowAliveWhenNoSteps: true
        EmrManagedMasterSecurityGroup: !Ref EMRSG
        EmrManagedSlaveSecurityGroup: !Ref EMRSG

  ### --- Cognito ---
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: StockAppUserPool
      AutoVerifiedAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: StockAppClient
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: StockAppIdentityPool
      AllowUnauthenticatedIdentities: false

Outputs:
  LoadBalancerDNS:
    Description: ALB endpoint for web app
    Value: !GetAtt ALB.DNSName

  RDSEndpoint:
    Description: PostgreSQL endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address

  DynamoDBTableName:
    Description: DynamoDB table name
    Value: !Ref DynamoDBTable

  StockPricesBucketName:
    Description: S3 bucket for stock prices
    Value: !Ref StockPricesBucket

  NewsArticlesBucketName:
    Description: S3 bucket for news articles
    Value: !Ref NewsArticlesBucket

  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool

  GlueJobName:
    Description: Glue Job for computing indicators
    Value: !Ref GlueJobComputeIndicators

  EMRClusterId:
    Description: EMR Cluster ID
    Value: !Ref EMRCluster
