SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmdGNyYnZhaWl3bGFoZWlia2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDA3MzYsImV4cCI6MjA3MjM3NjczNn0.HQc1yXzypLkmUIP_Xa1Ahy6UwpTsAOPbQA2ntSUcTvk"
SUPABASE_URL="https://xftcrbvaiiwlaheibkeb.supabase.co"
